# .pre-commit-config.yaml

repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # Use a stable Black version
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # Use the latest Ruff pre-commit version
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

default_stages: [commit, push]
