# config/config.yaml

cities:
  - name: New York
    state: New York
    station_id: GHCND:USW00094728
    region_code: NYIS

  - name: Chicago
    state: Illinois
    station_id: GHCND:USW00094846
    region_code: PJM

  - name: Houston
    state: Texas
    station_id: GHCND:USW00012960
    region_code: ERCO

  - name: Phoenix
    state: Arizona
    station_id: GHCND:USW00023183
    region_code: AZPS

  - name: Seattle
    state: Washington
    station_id: GHCND:USW00024233
    region_code: SCL
